### PR TITLE
fix build order

### LINKED ISSUE #80: Incorrect build order
`kie-wb-distribution` should be the last one to be built and not `jbpm-wb` as `jbpm-wb` repo artifacts are actually needed for `kie-wb-distributions` build.
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/compile/job/appformer-main.compile/244/consoleText

### PR DESCRIPTION
**Pull request by shubhbapna**
Fixes #80 

Say for example `projectB` depends on `projectC` and `projectA` depends on `projectB` and `projectC`. So the dependency graph looks like this:
```
projectB ---> projectC
    ^              ^
    |              |
projectA -----------
```
But in terms of purely just building `projectA` we just need to store the fact that `projectA` depends on `projectB` cause when we try to build `projectA` we will try to build `projectB`. But since `projectB` depends on `projectC` we will build that first. Therefore, we don't need to store the fact that `projectA` depends on `projectC` 

Moreover for `childChainFromNode` the issue was that we weren't adding all the children of a given node before we added all the grandchild of a child of the node i.e. we are doing depth first instead of breadth first

### CODE REVIEW

**Comment by Ginxo** [comment]
@shubhbapna I'm wondering... why don't you replicate the same piece of code from https://github.com/kiegroup/build-chain-configuration-reader/blob/ab0a664fe7a6c7fb95ec2903eb817629be4796fb/src/lib/tree-functionalities.js#LL22-L46 since it seems to be simpler? :thinking: 
anyway, thanks for the effort

**Comment by mareknovotny** [comment]
we should reuse existing method's or code which we know it works, so what we need to change this PR? @Ginxo
Could you suggest here the change?

File: src/tree.ts [hunk 1]
```diff
@@ -48,7 +48,8 @@ export async function getOrderedListForProject(
     throw new Error(`Project ${project} not found`);
   }
   const upstream: Node[] = parentChainFromNode(node); // last element is the current node
-  const downstream: Node[] = childChainFromNode(node); // first element is the current node
+  const downstream = [node];
+  childChainFromNode(node, downstream); // first element is the current node
   return upstream.concat(downstream.slice(1)); // avoid duplication of current node
 }
```
Comment (Ginxo) [inline src/tree.ts:54]: The change suggestion is close to this but I'm probably missing some TS refactoring, please add returned object type to the functions
```
async function getOrderedListForProject(
  definitionFileLocation: string,
  project: string,
  opts?: ReaderOpts
) : ¿PENDING? {
  const node = await getTreeForProject(definitionFileLocation, project, opts);
  if (!node) {
    throw new Error(`Project ${project} not found`);
  }
  return getOrderedList([tree]);
}

/**
 * Gets a plain node list of projects ordered by precedence
 * @param {string} node - The node to iterate
 */
async function getOrderedList(node: Node) {
  const finalLeaves = getFinalLeavesFromTree(node);
  return finalLeaves
    .map(leaf => parentChainFromNode(leaf))
    .sort((a, b) => b.length - a.length)
    .reduce((acc, chain) => {
      acc.push(
        ...chain.filter(c => !acc.map(e => e.project).includes(c.project))
      );
      return acc;
    }, []);
}

/**
 * It returns back the final leaves from a tree
 * @param {Array} nodes the array of nodes
 * @param {Array} latestLeavesFromTree
 * @param {Array} allreadyVisitedNodes
 */
function getFinalLeavesFromTree(
  nodes: Node[],
  latestLeavesFromTree = [],
  allreadyVisitedNodes = []
) {
  if (nodes && nodes.length > 0) {
    const allreadyVisitedPreviousNodes = [...allreadyVisitedNodes];
    const notIncludedChildren = nodes
      .filter(node => !allreadyVisitedPreviousNodes.includes(node.project))
      .reduce((acc, e) => {
        acc.push(
          ...e.children.filter(
            child => !acc.map(e => e.project).includes(child.project)
          )
        );
        return acc;
      }, []);
    allreadyVisitedNodes.push(...nodes.map(e => e.project));
    getFinalLeavesFromTree(
      notIncludedChildren,
      latestLeavesFromTree,
      allreadyVisitedNodes
    );

    latestLeavesFromTree.push(
      ...nodes.filter(
        node =>
          (!node.children || node.children.length === 0) &&
          !latestLeavesFromTree.map(e => e.project).includes(node.project)
      )
    );

    return latestLeavesFromTree;
  } else {
    return [];
  }
}
```

Comment (Ginxo) [reply src/tree.ts:54]: I remember we had a conversation about this specifically few months ago @shubhbapna right?

**Comment by Ginxo** [comment]
@shubhbapna don't forget to create https://github.com/kiegroup/github-action-build-chain PR pointing to the new version after merging (after publishing it)

File: src/tree.ts (hunk 1 above)
Comment (shubhbapna) [reply src/tree.ts:54]: Yep and the issue was that i was getting different output then what we were predicting based of on reading the code. so in the end we decided that i will implement it based on what we want to do rather than translating the existing code
